/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    experienceItems: ExperienceItem;
    skillGroups: SkillGroup;
    testimonials: Testimonial;
    submissions: Submission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    experienceItems: ExperienceItemsSelect<false> | ExperienceItemsSelect<true>;
    skillGroups: SkillGroupsSelect<false> | SkillGroupsSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    submissions: SubmissionsSelect<false> | SubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('ru' | 'en') | ('ru' | 'en')[];
  globals: {
    siteSettings: SiteSetting;
    homePage: HomePage;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    homePage: HomePageSelect<false> | HomePageSelect<true>;
  };
  locale: 'ru' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  displayName?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  enabled: boolean;
  order: number;
  title: string;
  description: string;
  result: string;
  accentColor?: string | null;
  image?: (number | null) | Media;
  cta: {
    label: string;
    href: string;
    openInNewTab?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experienceItems".
 */
export interface ExperienceItem {
  id: number;
  enabled: boolean;
  order: number;
  period: string;
  title: string;
  description: string;
  highlight: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skillGroups".
 */
export interface SkillGroup {
  id: number;
  enabled: boolean;
  order: number;
  title: string;
  level: string;
  description?: string | null;
  attachmentImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  enabled: boolean;
  order: number;
  quote: string;
  author: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions".
 */
export interface Submission {
  id: number;
  name: string;
  email: string;
  preferredChannel?: string | null;
  message: string;
  status?: ('new' | 'processed' | 'archived') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'experienceItems';
        value: number | ExperienceItem;
      } | null)
    | ({
        relationTo: 'skillGroups';
        value: number | SkillGroup;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'submissions';
        value: number | Submission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  enabled?: T;
  order?: T;
  title?: T;
  description?: T;
  result?: T;
  accentColor?: T;
  image?: T;
  cta?:
    | T
    | {
        label?: T;
        href?: T;
        openInNewTab?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experienceItems_select".
 */
export interface ExperienceItemsSelect<T extends boolean = true> {
  enabled?: T;
  order?: T;
  period?: T;
  title?: T;
  description?: T;
  highlight?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skillGroups_select".
 */
export interface SkillGroupsSelect<T extends boolean = true> {
  enabled?: T;
  order?: T;
  title?: T;
  level?: T;
  description?: T;
  attachmentImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  enabled?: T;
  order?: T;
  quote?: T;
  author?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "submissions_select".
 */
export interface SubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  preferredChannel?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  contactItems?:
    | {
        value: string;
        id?: string | null;
      }[]
    | null;
  socialLinks?:
    | {
        link: {
          label: string;
          href: string;
          openInNewTab?: boolean | null;
        };
        icon?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  defaultSEO: {
    title: string;
    description: string;
    ogImage?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage".
 */
export interface HomePage {
  id: number;
  hero: {
    enabled: boolean;
    order: number;
    eyebrow: string;
    name: string;
    title: string;
    description: string;
    primaryCta: {
      label: string;
      href: string;
      openInNewTab?: boolean | null;
    };
    secondaryCta: {
      label: string;
      href: string;
      openInNewTab?: boolean | null;
    };
    facts?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    portrait?: (number | null) | Media;
    portraitLabel?: string | null;
  };
  about: {
    enabled: boolean;
    order: number;
    title: string;
    body: string;
    principles?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    stats?:
      | {
          value: string;
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  skills: {
    enabled: boolean;
    order: number;
    title: string;
    subtitle: string;
    items?: (number | SkillGroup)[] | null;
  };
  experience: {
    enabled: boolean;
    order: number;
    title: string;
    subtitle: string;
    items?: (number | ExperienceItem)[] | null;
  };
  projects: {
    enabled: boolean;
    order: number;
    title: string;
    items?: (number | Project)[] | null;
  };
  testimonials: {
    enabled: boolean;
    order: number;
    title: string;
    subtitle: string;
    items?: (number | Testimonial)[] | null;
    signalTitle?: string | null;
    signalBody?: string | null;
  };
  preferences: {
    enabled: boolean;
    order: number;
    title: string;
    items?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
  };
  faq: {
    enabled: boolean;
    order: number;
    title: string;
    items?:
      | {
          question: string;
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  contact: {
    enabled: boolean;
    order: number;
    title: string;
    description: string;
    methods?:
      | {
          method: {
            label: string;
            href: string;
            openInNewTab?: boolean | null;
          };
          id?: string | null;
        }[]
      | null;
    formTitle: string;
    formDescription: string;
    privacyText: string;
  };
  footer: {
    enabled: boolean;
    order: number;
    copyright: string;
    links?:
      | {
          link: {
            label: string;
            href: string;
            openInNewTab?: boolean | null;
          };
          id?: string | null;
        }[]
      | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  contactItems?:
    | T
    | {
        value?: T;
        id?: T;
      };
  socialLinks?:
    | T
    | {
        link?:
          | T
          | {
              label?: T;
              href?: T;
              openInNewTab?: T;
            };
        icon?: T;
        id?: T;
      };
  defaultSEO?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homePage_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        enabled?: T;
        order?: T;
        eyebrow?: T;
        name?: T;
        title?: T;
        description?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              href?: T;
              openInNewTab?: T;
            };
        secondaryCta?:
          | T
          | {
              label?: T;
              href?: T;
              openInNewTab?: T;
            };
        facts?:
          | T
          | {
              text?: T;
              id?: T;
            };
        portrait?: T;
        portraitLabel?: T;
      };
  about?:
    | T
    | {
        enabled?: T;
        order?: T;
        title?: T;
        body?: T;
        principles?:
          | T
          | {
              text?: T;
              id?: T;
            };
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
      };
  skills?:
    | T
    | {
        enabled?: T;
        order?: T;
        title?: T;
        subtitle?: T;
        items?: T;
      };
  experience?:
    | T
    | {
        enabled?: T;
        order?: T;
        title?: T;
        subtitle?: T;
        items?: T;
      };
  projects?:
    | T
    | {
        enabled?: T;
        order?: T;
        title?: T;
        items?: T;
      };
  testimonials?:
    | T
    | {
        enabled?: T;
        order?: T;
        title?: T;
        subtitle?: T;
        items?: T;
        signalTitle?: T;
        signalBody?: T;
      };
  preferences?:
    | T
    | {
        enabled?: T;
        order?: T;
        title?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
      };
  faq?:
    | T
    | {
        enabled?: T;
        order?: T;
        title?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  contact?:
    | T
    | {
        enabled?: T;
        order?: T;
        title?: T;
        description?: T;
        methods?:
          | T
          | {
              method?:
                | T
                | {
                    label?: T;
                    href?: T;
                    openInNewTab?: T;
                  };
              id?: T;
            };
        formTitle?: T;
        formDescription?: T;
        privacyText?: T;
      };
  footer?:
    | T
    | {
        enabled?: T;
        order?: T;
        copyright?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    label?: T;
                    href?: T;
                    openInNewTab?: T;
                  };
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}